---
language: node_js

node_js:
  - "12"

cache: npm

script:
  - npm install
  - npm install codecov -g
  - npm run lint
  # Coverage report also runs the tests and will exit with a failure result if
  # the tests fail.
  - npm run-script coverage

after_success:
  - codecov
