name: Publish to GitHub Packages

on:
  release:
    types: [released, edited]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish to GitHub Packages
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'master'
          fetch-depth: 0
      - name: Authenticate with private NPM package
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          echo "@EssexManagement:registry=https://npm.pkg.github.com" >> ~/.npmrc
      - name: Copy latest release notes
        run: |
          tagName=$(gh release list --exclude-pre-releases --exclude-drafts --json tagName,isLatest -q '.[] | select(.isLatest == true) | .tagName')
          if [[ -z $tagName ]]; then
            echo "::error::Failed to find latest release"
            exit 1
          fi
          gh release view $tagName > LATEST-RELEASE.md
          if [[ -z "$(git status --porcelain)" ]]; then
            echo "Nothing to commit"
            exit 0
          fi
          # Note: the following account information will not work on GHES
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "[skip ci] save latest release notes"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to GitHub
        run: |
          npm version from-git
          git push
          npm publish
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
